### ISSUE TITLE
check opties bij Reacties verzamelen

### ISSUE THREAD

**Issue by jessicaslijpen** [jessicaslijpen/digitaal-bordje-MVP#10]

**Comment by ghost** [comment]
Als mensen worden uitgenodigd om in te vullen zijn er 6 invulbare velden. Kijken of opties willen of niet

**Comment by ghost** [comment]
- meerdere antwoorden toestaan (meer keer invullen vanaf hetzelfde apparaat) --> ja denk ik
- antwoorden wijzigen  (voor of nadat de enquete is voltooid) --> ja denk ik
- anonieme reacties (ip adressen ja of nee) --> maakt niet uit. nee is ook prima?
- direct resultaat (zie wat iedereen heeft ingevuld in pie charts ) --> definite no
- SSL-versleuteling --> geen idee
- uiterste datum en tijd dat het mag worden ingevuld --> nee lijkt me
- reactielimieten (maximaal aantal reacties) --> nee
IP-beperkingen (bepalen wie de enquete mag in vullen aan de hand van een ip adres --> nee
- Wachtwoordbeveiliging (alleen invullen met wachtwoord) --> nee
- Aangepast bedankbericht --> ja leuk
- Aangepaste diskwalificatie (Bij respondenten die via de logica voor overslaan in uw enquête worden gediskwalificeerd, wordt de optie weergeven die u hierna kiest) --> snap ik niet helemaal, maar denk het niet.
-Eindpagina van de enquete --> standaardpagina (nee!), aangepast (prima, maar niet nodig) of uit (venster sluiten of tabblad sluiten als de enquete voltooid is).

**Comment by ghost** [comment]
bedankbericht nog doen,  "tof we hopen dat dit geholpen heeft, bladiebla" eindpagina "verwijzing naar wehelpen"
